FROM node:10.15.3-alpine AS init
WORKDIR /usr/src/app
ENV NODE_ENV production
COPY package*.json ./
RUN npm ci --dev

FROM init AS build
COPY . .
RUN npm run build:prod
RUN npm prune --production

CMD npm run start:server:prod
EXPOSE 8080
