FROM node:10.15.3-alpine

WORKDIR /usr/src/app

ENV NODE_ENV production

COPY package*.json ./
RUN npm ci --dev

COPY . /usr/src/app
RUN npm run build:prod

CMD npm prune --production && npm run start:server:prod
EXPOSE 8080
