FROM node:10.15.3-alpine AS init
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV NODE_ENV production
COPY package*.json /usr/src/app/
RUN cd /usr/src/app && npm ci --dev

FROM init AS build
COPY . /usr/src/app
RUN npm run build:prod
RUN npm prune --production

FROM build AS final
CMD npm run start:server:prod
EXPOSE 8080
