export const MembersActionTypes = Object.freeze({
  ADD_FAILURE: 'member/ADD_FAILURE',
  ADD_REQUEST: 'member/ADD_REQUEST',
  ADD_SUCCESS: 'member/ADD_SUCCESS',
  CLEAR_DATA: 'members/CLEAR_DATA',
  COHORT_MEMBER_FAILURE: 'member/COHORT_MEMBER_FAILURE',
  COHORT_MEMBER_REQUEST: 'member/COHORT_MEMBER_REQUEST',
  COHORT_MEMBER_SUCCESS: 'member/COHORT_MEMBER_SUCCESS',
  COHORT_OWNER_FAILURE: 'member/COHORT_OWNER_FAILURE',
  COHORT_OWNER_REQUEST: 'member/COHORT_OWNER_REQUEST',
  COHORT_OWNER_SUCCESS: 'member/COHORT_OWNER_SUCCESS',
  FETCH_FAILURE: 'member/FETCH_FAILURE',
  FETCH_REQUEST: 'member/FETCH_REQUEST',
  FETCH_SUCCESS: 'member/FETCH_SUCCESS',
  REMOVE_FAILURE: 'member/REMOVE_FAILURE',
  REMOVE_REQUEST: 'member/REMOVE_REQUEST',
  REMOVE_SUCCESS: 'member/REMOVE_SUCCESS'
});
