export const UsersActionTypes = Object.freeze({
  COHORT_MEMBER_FAILURE: 'users/COHORT_MEMBER_FAILURE',
  COHORT_MEMBER_REQUEST: 'users/COHORT_MEMBER_REQUEST',
  COHORT_MEMBER_SUCCESS: 'users/COHORT_MEMBER_SUCCESS',
  COHORT_OWNER_FAILURE: 'users/COHORT_OWNER_FAILURE',
  COHORT_OWNER_REQUEST: 'users/COHORT_OWNER_REQUEST',
  COHORT_OWNER_SUCCESS: 'users/COHORT_OWNER_SUCCESS',
  FETCH_FAILURE: 'users/FETCH_FAILURE',
  FETCH_REQUEST: 'users/FETCH_REQUEST',
  FETCH_SUCCESS: 'users/FETCH_SUCCESS',
  REMOVE_FAILURE: 'users/REMOVE_FAILURE',
  REMOVE_REQUEST: 'users/REMOVE_REQUEST',
  REMOVE_SUCCESS: 'users/REMOVE_SUCCESS'
});
