export const MembersActionTypes = Object.freeze({
  ADD_FAILURE: 'member/ADD_FAILURE',
  ADD_REQUEST: 'member/ADD_REQUEST',
  ADD_SUCCESS: 'member/ADD_SUCCESS',
  CLEAR_DATA: 'member/CLEAR_DATA',
  MEMBER_FAILURE: 'member/MEMBER_FAILURE',
  MEMBER_REQUEST: 'member/MEMBER_REQUEST',
  MEMBER_SUCCESS: 'member/MEMBER_SUCCESS',
  OWNER_FAILURE: 'member/OWNER_FAILURE',
  OWNER_REQUEST: 'member/OWNER_REQUEST',
  OWNER_SUCCESS: 'member/OWNER_SUCCESS',
  FETCH_FAILURE: 'member/FETCH_FAILURE',
  FETCH_REQUEST: 'member/FETCH_REQUEST',
  FETCH_SUCCESS: 'member/FETCH_SUCCESS',
  REMOVE_FAILURE: 'member/REMOVE_FAILURE',
  REMOVE_REQUEST: 'member/REMOVE_REQUEST',
  REMOVE_SUCCESS: 'member/REMOVE_SUCCESS'
});
