export const CommentActionTypes = Object.freeze({
  ADD_FAILURE: 'comment/ADD_FAILURE',
  ADD_SUCCESS: 'comment/ADD_SUCCESS',
  FETCH_FAILURE: 'comment/FETCH_FAILURE',
  FETCH_SUCCESS: 'comment/FETCH_SUCCESS'
});

export const ItemActionTypes = Object.freeze({
  ADD_FAILURE: 'item/ADD_FAILURE',
  ADD_SUCCESS: 'item/ADD_SUCCESS',
  CLONE_FAILURE: 'item/CLONE_FAILURE',
  CLONE_SUCCESS: 'item/CLONE_SUCCESS',
  TOGGLE_FAILURE: 'item/TOGGLE_FAILURE',
  TOGGLE_SUCCESS: 'item/TOGGLE_SUCCESS',
  UPDATE_DETAILS_FAILURE: 'item/UPDATE_DETAILS_FAILURE',
  UPDATE_DETAILS_SUCCESS: 'item/UPDATE_DETAILS_SUCCESS',
  VOTE_FAILURE: 'item/VOTE_FAILURE',
  VOTE_SUCCESS: 'item/VOTE_SUCCESS'
});
