export const ShoppingListActionTypes = Object.freeze({
  FETCH_PRODUCTS_FAILURE: 'shopping-list/FETCH_PRODUCTS_FAILURE',
  FETCH_PRODUCTS_REQUEST: 'shopping-list/FETCH_PRODUCTS_REQUEST',
  CREATE_SHOPPING_LIST_SUCCESS: 'shopping-list/CREATE_SHOPPING_LIST_SUCCESS',
  CREATE_SHOPPING_LIST_FAILURE: 'shopping-list/CREATE_SHOPPING_LIST_FAILURE',
  FETCH_SHOPPING_LISTS_SUCCESS: 'shopping-list/FETCH_SHOPPING_LISTS_SUCCESS',
  FETCH_SHOPPING_LISTS_FAILURE: 'shopping-list/FETCH_SHOPPING_LISTS_FAILURE'
});
