export const ShoppingListActionTypes = Object.freeze({
  ADD_SHOPPING_LIST_SUCCESS: 'shopping-list/ADD_SHOPPING_LIST_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'shopping-list/FETCH_PRODUCTS_FAILURE',
  FETCH_SHOPPING_LISTS_META_DATA_SUCCESS:
    'shopping-list/FETCH_SHOPPING_LISTS_META_DATA_SUCCESS',
  FETCH_SHOPPING_LISTS_SUCCESS: 'shopping-list/FETCH_SHOPPING_LISTS_SUCCESS',
  FETCH_PRODUCTS_SUCCESS: 'shopping-list/FETCH_PRODUCTS_SUCCESS'
});

// usun shopping list
