export const ShoppingListActionTypes = Object.freeze({
  CREATE_SHOPPING_LIST_FAILURE: 'shopping-list/CREATE_SHOPPING_LIST_FAILURE',
  CREATE_SHOPPING_LIST_REQUEST: 'shopping-list/CREATE_SHOPPING_LIST_REQUEST',
  CREATE_SHOPPING_LIST_SUCCESS: 'shopping-list/CREATE_SHOPPING_LIST_SUCCESS',
  DELETE_FAILURE: 'shopping-list/DELETE_FAILURE',
  DELETE_REQUEST: 'shopping-list/DELETE_REQUEST',
  DELETE_SUCCESS: 'shopping-list/DELETE_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'shopping-list/FETCH_PRODUCTS_FAILURE',
  FETCH_PRODUCTS_REQUEST: 'shopping-list/FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'shopping-list/FETCH_PRODUCTS_SUCCESS',
  FETCH_META_DATA_SUCCESS: 'shopping-list/FETCH_META_DATA_SUCCESS',
  FETCH_META_DATA_FAILURE: 'shopping-list/FETCH_META_DATA_FAILURE',
  FETCH_META_DATA_REQUEST: 'shopping-list/FETCH_META_DATA_REQUEST'
});
