export const CohortActionTypes = Object.freeze({
  CREATE_COHORT_FAILURE: 'cohort/CREATE_COHORT_FAILURE',
  CREATE_COHORT_REQUEST: 'cohort/CREATE_COHORT_REQUEST',
  CREATE_COHORT_SUCCESS: 'cohort/CREATE_COHORT_SUCCESS',
  FETCH_COHORTS_FAILURE: 'cohort/FETCH_COHORTS_FAILURE',
  FETCH_COHORTS_REQUEST: 'cohort/FETCH_COHORTS_REQUEST',
  FETCH_COHORTS_SUCCESS: 'cohort/FETCH_COHORTS_SUCCESS'
});
