export const CohortActionTypes = Object.freeze({
  CREATE_COHORT_FAILURE: 'cohort/CREATE_COHORT_FAILURE',
  CREATE_COHORT_REQUEST: 'cohort/CREATE_COHORT_REQUEST',
  CREATE_COHORT_SUCCESS: 'cohort/CREATE_COHORT_SUCCESS',
  FETCH_META_DATA_FAILURE: 'cohort/FETCH_META_DATA_FAILURE',
  FETCH_META_DATA_REQUEST: 'cohort/FETCH_META_DATA_REQUEST',
  FETCH_META_DATA_SUCCESS: 'cohort/FETCH_META_DATA_SUCCESS'
});
