export const ItemActionTypes = Object.freeze({
  ADD_ITEM_FAILURE: 'item/ADD_ITEM_FAILURE',
  ADD_ITEM_REQUEST: 'item/ADD_ITEM_REQUEST',
  ADD_ITEM_SUCCESS: 'item/ADD_ITEM_SUCCESS',
  TOGGLE_ITEM_FAILURE: 'item/TOGGLE_ITEM_FAILURE',
  TOGGLE_ITEM_REQUEST: 'item/TOGGLE_ITEM_REQUEST',
  TOGGLE_ITEM_SUCCESS: 'item/TOGGLE_ITEM_SUCCESS',
  VOTE_FOR_ITEM_FAILURE: 'item/VOTE_FOR_ITEM_FAILURE',
  VOTE_FOR_ITEM_REQUEST: 'item/VOTE_FOR_ITEM_REQUEST',
  VOTE_FOR_ITEM_SUCCESS: 'item/VOTE_FOR_ITEM_SUCCESS'
});
