export const ProductActionTypes = Object.freeze({
  ADD_PRODUCT_FAILURE: 'product/ADD_PRODUCT_FAILURE',
  ADD_PRODUCT_REQUEST: 'product/ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_SUCCESS: 'product/ADD_PRODUCT_SUCCESS',
  TOGGLE_PRODUCT_FAILURE: 'product/TOGGLE_PRODUCT_FAILURE',
  TOGGLE_PRODUCT_REQUEST: 'product/TOGGLE_PRODUCT_REQUEST',
  TOGGLE_PRODUCT_SUCCESS: 'product/TOGGLE_PRODUCT_SUCCESS',
  VOTE_FOR_PRODUCT_FAILURE: 'product/VOTE_FOR_PRODUCT_FAILURE',
  VOTE_FOR_PRODUCT_REQUEST: 'product/VOTE_FOR_PRODUCT_REQUEST',
  VOTE_FOR_PRODUCT_SUCCESS: 'product/VOTE_FOR_PRODUCT_SUCCESS'
});
