export const ItemActionTypes = Object.freeze({
  ADD_DETAILS_FAILURE: 'item/ADD_DETAILS_FAILURE',
  ADD_DETAILS_REQUEST: 'item/ADD_DETAILS_REQUEST',
  ADD_DETAILS_SUCCESS: 'item/ADD_DETAILS_SUCCESS',
  ADD_FAILURE: 'item/ADD_FAILURE',
  ADD_REQUEST: 'item/ADD_REQUEST',
  ADD_SUCCESS: 'item/ADD_SUCCESS',
  TOGGLE_FAILURE: 'item/TOGGLE_FAILURE',
  TOGGLE_REQUEST: 'item/TOGGLE_REQUEST',
  TOGGLE_SUCCESS: 'item/TOGGLE_SUCCESS',
  VOTE_FAILURE: 'item/VOTE_FAILURE',
  VOTE_REQUEST: 'item/VOTE_REQUEST',
  VOTE_SUCCESS: 'item/VOTE_SUCCESS'
});
