export const ItemActionTypes = Object.freeze({
  ADD_DESCRIPTION_FAILURE: 'item/ADD_DESCRIPTION_FAILURE',
  ADD_DESCRIPTION_REQUEST: 'item/ADD_DESCRIPTION_REQUEST',
  ADD_DESCRIPTION_SUCCESS: 'item/ADD_DESCRIPTION_SUCCESS',
  ADD_FAILURE: 'item/ADD_FAILURE',
  ADD_LINK_FAILURE: 'item/ADD_LINK_FAILURE',
  ADD_LINK_REQUEST: 'item/ADD_LINK_REQUEST',
  ADD_LINK_SUCCESS: 'item/ADD_LINK_SUCCESS',
  ADD_REQUEST: 'item/ADD_REQUEST',
  ADD_SUCCESS: 'item/ADD_SUCCESS',
  TOGGLE_FAILURE: 'item/TOGGLE_FAILURE',
  TOGGLE_REQUEST: 'item/TOGGLE_REQUEST',
  TOGGLE_SUCCESS: 'item/TOGGLE_SUCCESS',
  VOTE_FAILURE: 'item/VOTE_FAILURE',
  VOTE_REQUEST: 'item/VOTE_REQUEST',
  VOTE_SUCCESS: 'item/VOTE_SUCCESS'
});
